[package]
name = "aoc_4"
version = "0.1.0"
authors = ["ianhoffman <ijh6@cornell.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.5"
chrono = "0.4.0"
